#! /bin/bash

error(){
    echo "Command not found!"
    echo "Run 'bash hasan help' for usage."
    exit 1
}

need_second_param(){
    if [ $1 != 2 ]
    then
        echo "Need second param!"
        echo "Run 'bash hasan help' for usage."
        exit 1
    fi   
}

help(){
cat << 'EOF'
Usage
    bash hasan [command] [param]
command
    deploy [commit -m content]    # 部署到Github
    run [default=1313]            # 本地运行
    new [name]                    # 创建新文章
    books                         # 更新图书库
    help                          # 帮助
EOF
}

books(){
article_path=$(pwd)"/content/posts/2019/20191231-books.md"
(
cat << 'EOF'
---
title: "书籍"
date: 2019-12-31T17:57:29+08:00
toc: true
---
意图打造一个在线图书库，收藏一些平时遇到又觉得不错的书籍，自动化脚本已写好，每次只需往书库里添加PDF文件即可，本文便是通过脚本检测动态生成。
因为懒得维护服务器我整个博客都是挂在Github上，众所周知的原因导致看PDF有时会很慢，咳 ~
<!--more-->
EOF
) > $article_path

books_path=$(pwd)"/content/assets/books/"
books=$(ls $books_path)

for files in $books
do
    category=$(ls $books_path$files)
    echo -e "\n### "$files >> $article_path
    for book in $category
    do
        url="<a href=\"https://hasan.shaobo.fun/assets/books/"$files"/"$book"\" target=\"_blank\">"${book%.pdf}"</a>\n"
        echo -e $url >> $article_path
    done
done
}

if [ $# -lt 1 ]
then
    error
fi

# 部署到Github
if [ $1 == "deploy" ]
then
    need_second_param $#
    books
    commit_msg="$2"

    hugo -d docs
    git add .
    git commit -m "$commit_msg"
    git push origin master

    echo "Deploy success!"

# 本地运行
elif [ $1 == "run" ]
then
    port="1313"

    if [ $# == 2 ]
    then
        port=$2
    fi

    url="http://localhost:"$port
    open $url #in macOS
    $(hugo server -D -p $port)

# 新建文章
elif [ $1 == "new" ]
then
    need_second_param $#

    year=$(date +%Y)
    folder="posts/"$year

    name=$2
	date=$(date "+%Y%m%d")
	title=$date"-"$name".md"
	file_path=$folder"/"$title

	hugo new $file_path
	echo "markdown file "$title
    echo "Created in the posts folder!"

# 更新图书库
elif [ $1 == "books" ]
then
    books

# 帮助
elif [ $1 == "help" ]
then
    help
else
    error
fi
